<template>
    <div style="display: flex; margin: 5px 0">
        <el-text class="hint mx-1">
            <el-tag type="primary" effect="light">Headers</el-tag>
        </el-text>
    </div>
    <div class="headers-editor">
        <el-table
            ref = "multiple_table_ref"
            :data="temp_headers"
            style="width: 100%"
            border
            table-layout="auto"
            @selection-change = "handleSelectionChange"
        >
            <el-table-column type="selection" width="55"/>
            <el-table-column label="Key" width="270">
                <template #default="scope">
                    <el-input
                        :disabled="!scope.row.usr_editable"
                        v-model="scope.row.k"
                        style="width: 100%"
                        placeholder="Key"/>
                </template>
            </el-table-column>
            <el-table-column label="Value" width="370">
                <template #default="scope">
                    <el-input
                        :disabled="!scope.row.usr_editable"
                        v-model="scope.row.v"
                        style="width: 100%"
                        placeholder="Value"/>
                </template>
            </el-table-column>
            <el-table-column
                label="Descriptor">
                <template #default="scope">
                    <el-input
                        :disabled="!scope.row.usr_editable"
                        v-model="scope.row.descriptor"
                        style="width: 100%"
                        placeholder="Descriptor"/>
                </template>
            </el-table-column>
        </el-table>
    </div>
</template>

<script setup>
import builder from '../../../TestBuilder.js'
import {onMounted, ref, watch} from "vue";

const props = defineProps(['temp_test']);
const temp_request = props.temp_test.request;
const multiple_table_ref = ref(null);
let temp_headers = temp_request.headers;
let mounted = 0;

if (temp_headers.length === 0) {
    temp_headers.push( ... builder.newAutoGeneratedHeaders() );
}

const handleSelectionChange = (selected_headers) => {
    if(mounted !== 0) {
        temp_headers.forEach((header) => {
            header.selected = selected_headers.includes(header);
        })
    }
}

onMounted(()=>{
    temp_headers.forEach((header) => {
        multiple_table_ref.value.toggleRowSelection(header, header.selected);
    })
    mounted = 1;
})

watch(temp_headers,
    ()=>{
        temp_headers.forEach((header) => {
            multiple_table_ref.value.toggleRowSelection(header, header.selected);
        })
    },
    {deep: true})
</script>

<style scoped>
::v-deep(.el-text) {
    display: block;
    text-align: left;
}
</style>